[package]
name = "chemical-ui"
publish = false
version = "0.0.0"
authors = ["Aster <192607617@qq.com>"]
description = "rationalize float to ratio"
repository = "https://github.com/oovm/chemical-balancer/tree/dev/projects/rationalize"
documentation = "https://docs.rs/rationalize"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[[bin]]
name = "chemical-web"
path = "website/main.rs"

[[bin]]
name = "chemical-balancer"
path = "desktop/main.rs"

[dependencies]
dioxus = "0.6.3"
dioxus-desktop = "0.6.3"
dioxus-web = "0.6.3"
dioxus-hooks-plus = "0.2.1"

[dependencies.chemical-balancer]
version = "*"
path = "../chemical-balancer"

[dev-dependencies]
image = "0.25.5"

[features]
default = []
